### ISSUE TITLE
Launch Issue with ENSnano 0.5.1.1 on Apple M1 MacBook Pro

### ISSUE THREAD

**Issue by dfajita** [ensnano/ensnano#1]
Hi there! First off, a huge thank you for the updates and improvements! Just noticed the new version release today 🎉  I'm on a MacBook Pro with an Apple M1 Chip, running macOS Sonoma 14.3. Encountered an issue launching the "Mac OS 11.0+ with Apple silicon chip" binary (version 0.5.1.1) from https://www.ens-lyon.fr/ensnano/. I got this error: 

> “ENSnano is damaged and can’t be opened. You should move it to the Trash.” 

Any help with this issue would be appreciated. Thanks!

**Comment by ensnano** [comment]
This is a paranoid security measure by MacOS. Here is the trick (as suggested in the release notes):
"in order to pass MAC OS security check, please Open a Terminal and change the directory to the path to your ENSnano.app and type "sh RUN_ME_FIRST.sh". For the curious, it executes the command "xattr -cr /path_to_ENSnano/ENSnano.app" which unlocks the app"
I hope this helps
